//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Customer = new HashSet<Customer>();
        }
    
        public int userID { get; set; }
        public string passWord { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string email { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> MaLoaiTV { get; set; }
        public string ResetPassWordCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual LoaiThanhVien LoaiThanhVien { get; set; }
    }
}
